server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.144.88:3306/game?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false
    username: root
    password: 123456

  redis:
    host: 116.62.144.88
    port: 6379
    password:
    timeout: 30000




